### ISSUE TITLE
Error on load save (migrating from 0.0.26 to 0.0.30 mod ver.)

### ISSUE THREAD

**Issue by malomaster** [millerscout/MMD-Factorio-Mods#10]
```
Mod Quality of Life research (3.3.0) got an exception.

Error while running event qol_research::on_configuration_changed
Mod Experience for buildings (Опытные машины) (0.0.30) got an exception.

Error while running event xp-for-buildings::on_research_finished (ID 18)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__xp-for-buildings__/control.lua:623: in function <__xp-for-buildings__/control.lua:620>
stack traceback:
	[C]: in function '__newindex'
	__qol_research__/control.lua:139: in function 'update_for_force_and_category'
	__qol_research__/control.lua:160: in function 'update_for_force'
	__qol_research__/control.lua:169: in function 'update_for_all_forces'
	__qol_research__/control.lua:241: in function <__qol_research__/control.lua:236>
```
Got this error when I loaded the last mod version and tried to load my last save.
New game started without this error.
Here is the string for QoL's "Custom config" setting (there is a possibility that the problem is in them): `1,17,crafting-speed,150*L,automation-science-pack,logistic-science-pack,175*L,chemical-science-pack,225*L,production-science-pack,300*L,space-science-pack,250*1.2^(L-1),inventory-size,utility-science-pack,500*1.2^(L-1),mining-speed,movement-speed,player-reach,5,1,5,5,20,0,0,2,10,1,1,3,5,20,3,1,4,5,15,2,1,3,1,4,5,15,3,1,6,7,20,3,1,3,1,4,1,6,5,15,3,1,8,9,25,4,1,3,1,4,1,6,1,8,0,10,5,1,10,11,30,5,1,3,1,4,1,6,1,8,1,10,12,5,2,5,0,0,2,10,1,1,3,4,5,1,1,4,5,15,2,1,3,1,4,6,5,1,1,6,7,20,3,1,3,1,4,1,6,8,5,2,1,13,9,25,4,1,3,1,4,1,6,1,13,0,5,4,1,10,14,30,5,1,3,1,4,1,6,1,13,1,10,15,5,5,30,0,0,2,10,1,1,3,5,25,3,1,4,5,15,2,1,3,1,4,5,20,3,1,6,7,20,3,1,3,1,4,1,6,5,15,3,1,8,9,25,4,1,3,1,4,1,6,1,8,0,10,5,1,10,11,30,5,1,3,1,4,1,6,1,8,1,10,16,5,4,5,0,0,2,10,1,1,3,4,5,2,1,4,5,15,2,1,3,1,4,4,5,2,1,6,7,20,3,1,3,1,4,1,6,4,5,2,1,13,9,25,4,1,3,1,4,1,6,1,13,0,5,4,1,10,11,30,5,1,3,1,4,1,6,1,13,1,10,17,5,2,1,0,0,2,10,1,1,3,3,1,2,1,4,5,15,2,1,3,1,4,4,1,2,1,6,7,20,3,1,3,1,4,1,6,25,1,2,1,8,9,25,4,1,3,1,4,1,6,1,8,0,1,3,1,10,14,30,5,1,3,1,4,1,6,1,8,1,10`
And here is my [save](https://drive.google.com/file/d/1shwdGAQj3DowuxQPM0IWegMxzewgwwuQ/view?usp=share_link) on google drive.

**Comment by millerscout** [comment]
your save game doesn't load 😓 
but i'm trying another way of fix
