### ISSUE TITLE
Failed to load the py module

### ISSUE THREAD

**Issue by moran0027** [millerscout/MMD-Factorio-Mods#2]
Thanks for your reply! I am a new py module as long as you join the module game loading error. Can't get into the game at all.
[py.zip](https://github.com/millerscout/MMD-Factorio-Mods/files/12836701/py.zip)

**Comment by millerscout** [comment]
fixed with 0.0.12

**Comment by moran0027** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
