### ISSUE TITLE
Crash when picking up some items from the Ruins mod

### ISSUE THREAD

**Issue by DrWiFi** [millerscout/MMD-Factorio-Mods#4]
Hello,
I've received this a couple of times while picking up buildings generated from the Ruins mod

<img width="558" alt="Screenshot 2023-10-10 at 2 30 49 PM" src="https://github.com/millerscout/MMD-Factorio-Mods/assets/50341031/c0cfb170-2601-4001-9eda-5cab68644448">

**Comment by DrWiFi** [comment]
Also received this in Factory Planner:
<img width="558" alt="Screenshot 2023-10-10 at 2 53 15 PM" src="https://github.com/millerscout/MMD-Factorio-Mods/assets/50341031/d95f3846-985c-485e-b69b-fd49802bc687">

**Comment by millerscout** [comment]
thanks for reporting
fixed on 0.0.18
